name: version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'tag version of the latest release'
        required: true
        type: string

jobs:
  write-version:
    runs-on: ubuntu-latest
    name: Write Version to File
    steps:
    - uses: actions/checkout@master
    - name: Update version
      uses: brettdorrans/write-version-to-file@master
      with:
        filename: './version.txt'
        placeholder: ${{inputs.VERSION}}
